### PR TITLE
#9 Format the code base

### PR DESCRIPTION
**Pull request by gaufung**

### CODE REVIEW

**Comment by observeralone** [comment]
This PR package does not pass. Please run `source.sh` or `source.cmd` to try to pass the package. At the same time, fix the bug and submit it again. Thank you.

**Comment by gaufung** [comment]
ah. Looks like it missing the build pipeline.

**Comment by observeralone** [comment]
This project currently lacks the GitHub `workflow` to better verify the usability of the code. If you are interested, you can try adding. #11

**Comment by gaufung** [comment]
Sure. Will take look at it.

**Review by observeralone — APPROVED** [review]

**Pull request merged**
